config/routes.rb
Cats::Application.routes.draw do

  resources :cats do
    member do
      resources :cat_rental_requests, only: [:new, :create]
    end
  end

  put 'cat_rental_requests/:id/approve', to: 'cat_rental_requests#approve', as: 'approve_rental_request'
  put 'cat_rental_requests/:id/deny', to: 'cat_rental_requests#deny', as: 'deny_rental_request'

  resources :users, only: [:new, :create, :show]
  resources :sessions, only: [:new, :create]
  delete 'sessions', to: 'sessions#destroy', as: 'delete_session'

end

app/models/cat.rb
class Cat < ActiveRecord::Base
  attr_accessible :age, :birth_date, :color, :name, :sex, :user_id

  validates :age, :birth_date, :color, :name, :sex, :presence => true
  validates :age, :numericality => { :only_integer => true }
  validates :color, :inclusion => { :in => %w[white black grey] }
  validates :sex, :inclusion => { :in => %w[M F] }

  has_many :cat_rental_requests, dependent: :destroy

  belongs_to :owner, class_name: "User", foreign_key: :user_id
end

app/models/cat_rental_request.rb
class CatRentalRequest < ActiveRecord::Base
  attr_accessible :cat_id, :start_date, :end_date, :status

  validates :cat_id, :start_date, :end_date, :status, presence: true
  validates :status, inclusion: {in: %w(PENDING APPROVED DENIED)}
  validate  :overlapping_approved_requests

  belongs_to :cat

  before_validation do
    self.status ||= "PENDING"
  end

  def overlapping_requests
    sql = <<-SQL
            #{self.cat_id} = cat_rental_requests.cat_id
    AND     ("#{self.start_date}" BETWEEN cat_rental_requests.start_date AND cat_rental_requests.end_date
    OR       "#{self.end_date}" BETWEEN cat_rental_requests.start_date AND cat_rental_requests.end_date
    OR        cat_rental_requests.start_date BETWEEN "#{self.start_date}" AND "#{self.end_date}"
    OR        cat_rental_requests.end_date BETWEEN "#{self.start_date}" AND "#{self.end_date}")
    SQL

    CatRentalRequest.where(sql)
  end

  def overlapping_approved_requests
    if self.id
      if overlapping_requests.where(:status => "APPROVED").count > 1
        errors[:request] << "can't overlap with other approved requests"
      end
    else
      if overlapping_requests.where(:status => "APPROVED").count > 0
        errors[:request] << "can't overlap with other approved requests"
      end
    end
  end

  def overlapping_pending_requests
    overlapping_requests.where(:status => "PENDING")
  end

  def approve!
    CatRentalRequest.transaction do
      overlapping_pending_requests.each do |request|
        request.deny!
      end
      self.update_attributes(:status => "APPROVED")
    end
  end

  def deny!
    self.update_attributes(:status => "DENIED")
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  attr_accessible :user_name, :password
  attr_reader :password

  before_validation :ensure_session_token
  validates :user_name, :password_digest, :session_token, presence: true
  validates :user_name, uniqueness: true

  has_many :cats


  def self.generate_session_token
    SecureRandom::urlsafe_base64(16)
  end

  def reset_session_token!
    self.session_token = self.class.generate_session_token
    self.save!
  end

  def password=(password)
    @password = password
    self.password_digest = BCrypt::Password.create(password)
  end

  def is_password?(password)
    BCrypt::Password.new(self.password_digest).is_password?(password)
  end

  def self.find_by_credentials(user_name, password)
    user = User.find_by_user_name(user_name)

    return nil if user.nil?

    user.is_password?(password) ? user : nil
  end

  def ensure_session_token
    self.session_token ||= self.class.generate_session_token
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  include SessionsHelper
  protect_from_forgery
end

app/controllers/cat_rental_requests_controller.rb
class CatRentalRequestsController < ApplicationController
  before_filter :require_current_user!, only: [:approve, :deny]

  def new
    @cat = Cat.find(params[:id])
    render :new
  end

  def create
    @request = CatRentalRequest.new(params[:cat_rental_request])
    unless @request.save
      flash[:errors] ||= []
      flash[:errors] << @request.errors.full_messages.to_sentence
    end
    redirect_to Cat.find(params[:id])
  end

  def approve
    @request = CatRentalRequest.find(params[:id])
    @cat = Cat.find(@request.cat_id)


    if current_user.cats.include?(@cat)
      @request.approve!
    else
      flash[:errors] = "Cat doesn't belong to you!"
    end
    redirect_to @cat
  end

  def deny
    @request = CatRentalRequest.find(params[:id])
    @cat = Cat.find(@request.cat_id)

    if current_user.cats.include?(@cat)
      @request.deny!
    else
      flash[:errors] = "Cat doesn't belong to you!"
    end
    redirect_to @cat
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_filter :require_current_user!, except: [:index, :show]

  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
    @cat_rental_requests = @cat.cat_rental_requests
  end

  def new
    @cat = Cat.new
  end

  def create
    attrs = params[:cat]
    attrs[:user_id] = self.current_user.id
    @cat = Cat.new(attrs)
    if @cat.save
      redirect_to @cat
    else
      flash[:errors] ||= []
      flash[:errors] << @cat.errors.full_messages.to_sentence
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    redirect_to cats_url if current_user != @cat.owner
  end

  def update
    redirect_to cats_url if current_user != cat.owner
    @cat = Cat.find(params[:id])
    if @cat.update_attributes(params[:cat])
      redirect_to @cat
    else
      flash[:errors] ||= []
      flash[:errors] << @cat.errors.full_messages.to_sentence
      render :edit
    end
  end
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def create
    user = User.find_by_credentials(
      params[:user][:username],
      params[:user][:password]
    )

    if user.nil?
      flash.now[:errors] = "Credentials were wrong"
    else
      user.reset_session_token!
      self.current_user = user
      redirect_to user_url(user)
    end
  end

  def new
  end

  def destroy
    self.current_user.reset_session_token!
    session[:session_token] = nil
    redirect_to cats_url
  end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_filter :require_current_user!, only: :show

  def new
    @user = User.new
  end

  def create
    @user = User.new(params[:user])

    if @user.save
      self.current_user = @user
      redirect_to user_url(@user)
    else
      flash.now[:errors] = @user.errors.full_messages
      redirect_to cats_url
    end
  end

  def show
    if params.include?(:id) && current_user.id == params[:id].to_i
      @user = current_user
      @cats = @user.cats
    else
      redirect_to user_url(current_user)
    end
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cat_rental_requests_helper.rb
module CatRentalRequestsHelper
end

app/helpers/cats_helper.rb
module CatsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
  def current_user
    User.find_by_session_token(session[:session_token])
  end

  def current_user=(user)
    @current_user = user
    session[:session_token] = user.session_token
  end

  def require_current_user!
    redirect_to new_session_url if current_user.nil?
  end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cat_rental_requests/new.html.erb
<h1>New Rental Request</h1>

<form action="/cats/<%= @cat.id %>/cat_rental_requests" method="post">
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">

  <input type="hidden" name="cat_rental_request[cat_id]" value="<%= @cat.id %>">

  <label for="start_date">Start Date:</label>
  <input type="date" name="cat_rental_request[start_date]">
  <br><br>

  <label for="end_date">End Date:</label>
  <input type="date" name="cat_rental_request[end_date]">
  <br><br>

  <input type="submit" value="Submit Request">

</form>

app/views/cats/_form.html.erb
 <% if @cat.persisted? %>
    <form action="/cats/<%= @cat.id %>" method="post">
    <input type="hidden" name="_method" value="put">
  <% else %>
    <form action="/cats" method="post">
  <% end %>

  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">
  <label for="cat_name">Name</label>
  <input type="text" name="cat[name]" id="cat_name" value="<%= @cat.name %>">
  <br><br>

  <label for="cat_age">Age</label>
  <input type="text" name="cat[age]" id="cat_age" value="<%= @cat.age %>">
  <br><br>

  <input type="radio" name="cat[sex]" id="cat_sex_female" value="F" <%= "checked" if @cat.sex == "F"%>>
  <label for="cat_sex_female">Female</label>
  <input type="radio" name="cat[sex]" id="cat_sex_male" value="M" <%= "checked" if @cat.sex == "M"%>>
  <label for="cat_sex_male">Male</label>
  <br><br>

  <label for="cat_color">Color</label>
  <select name="cat[color]" id="cat_color">
    <option></option>
    <option value="black" <%= "selected" if @cat.color == "black"%>>Black</option>
    <option value="white" <%= "selected" if @cat.color == "white"%>>White</option>
    <option value="grey" <%= "selected" if @cat.color == "grey"%>>Grey</option>
  </select>
  <br><br>

  <input type="date" name="cat[birth_date]" value="<%= @cat.birth_date %>">
  <br><br>

  <% if @cat.persisted? %>
     <input type="submit" value="Update cat">
   <% else %>
     <input type="submit" value="Create cat">
   <% end %>

</form>

app/views/cats/edit.html.erb
<h1>Edit a Cat</h1>

<%= render "form" %>

app/views/cats/index.html.erb
<h1>Cats</h1>
<% @cats.each do |cat| %>
  <p>Name: <%=link_to cat.name, cat %> </p>
<% end %>

app/views/cats/new.html.erb
<h1>Post a Cat</h1>

<%= render "form" %>

app/views/cats/show.html.erb
<h1><%= link_to @cat.name, "#{@cat.id}/edit" %></h1>

<table>
  <tr>
    <th>Name</th>
    <th>Age</th>
    <th>Birth Date</th>
    <th>Color</th>
    <th>Sex</th>
  </tr>
  <tr>
    <td><%= @cat.name %></td>
    <td><%= @cat.age %></td>
    <td><%= @cat.birth_date %></td>
    <td><%= @cat.color %></td>
    <td><%= @cat.sex %></td>
  </tr>
</table>

<h3>Cat Rental Requests</h3>

<%= link_to "Make a Request", new_cat_rental_request_url%>


<% @cat_rental_requests.each do |request|%>
  <p>Start Date: <%= request.start_date%>  End Date: <%= request.end_date%>  Status: <%= request.status%>

    <%= button_to "Approve", approve_rental_request_url(request), method: "put" %>
    <%= button_to "Deny", deny_rental_request_url(request), method: "put" %>
  </p>
<% end%>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Cats</title>
  <%#= stylesheet_link_tag    "application", :media => "all" %>
  <%#= javascript_include_tag "application" %>
  <%#= csrf_meta_tags %>
</head>
<body>
<%= debug params %>

<% if flash[:errors] %>
   <%= flash[:errors] %>
   <br><br>
<% end %>

<% if current_user.nil? %>
  <%= link_to "Log In", new_session_url %>
<% else %>
  <%= link_to "Hello, #{current_user.user_name}", user_url(current_user)%>
  <br><br>
  <%= button_to "Log Out", delete_session_url, method: "delete"%>
<% end %>
<%= yield %>

</body>
</html>

app/views/users/new.html.erb
<h1> Create an Account </h1>
<form action="<%= users_url %>" method="post">
  <input type="hidden"
           name="authenticity_token"
           value="<%= form_authenticity_token %>">

  <label for="user_name">Username</label>
  <input type="text" name="user[user_name]" id="user_name">
  <br><br>

  <label for="password">Password</label>
  <input type="password" name="user[password]" id="password">
  <br><br>

  <input type="submit" value="Create an Account">
</form>

app/views/users/show.html.erb
<h1>User's Profile Page</h1>

<p>Your user_name: <%= @user.user_name %></p>
<p><%= link_to "Rent a cat today!", cats_url%>

<p><%= link_to "Add Your Cat", new_cat_url %></p>

<h1>Cats</h1>

<% @cats.each do |cat| %>
  <p>Name: <%=link_to cat.name, cat %> </p>
<% end %>